apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomodoro-dep
  labels:
    app: pomodoro
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pomodoro
  template:
    metadata:
      labels:
        app: pomodoro
    spec:
      containers:  
      - name: pomodoro
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: container-port
        resources:
          requests:
            memory: {{ .Values.memoryRequest }}
            cpu: {{ .Values.cpuRequest }}
          limits:
            memory: {{ .Values.memoryLimit }}
            cpu: {{ .Values.cpuLimit }}