apiVersion: v1
kind: Service
metadata:
  name: palestine-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: palestine
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}