---
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: true

- name: Download Docker GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  register: download_key

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present
    filename: docker
    update_cache: yes

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

- name: Add user permissions
  ansible.builtin.user:
    name: "thomas"
    append: true
    groups: docker

- name: Reset SSH connection
  ansible.builtin.meta: "reset_connection"

