---
- name: Install docker on the machine
  hosts: app
  become: true
  roles:
    - docker
  tasks:
    - name: Pull the latest image
      docker_image:
        name: thomasrsc/pomd
        tag: latest
        source: pull

    - name: Deploy the app container
      docker_container:
        name: pomodoro
        image: thomasrsc/pomd
        state: started
        ports:
          - "80:5000"