name: CI/CD Pipline
on:
  push:
      branches:
         -  master
      tags:
         -  '*'
jobs:
   lint-and-test:
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout code
            uses: actions/checkout@v4

         -  name: set up python
            uses: actions/setup-python@v5
            with:
               python-version: "3.9" 

         -  name: install dependecies
            run:
               pip install -r requirements.txt
               
         -  name: Verify Python setup
            run:  |
               python --version
               pip list
         
         -  name: Run tests 
            run: python -m unittest discover tests/

   build-and-push:
      needs: lint-and-test
      runs-on: ubuntu-latest

      steps:
         -  name: Chekout code 
            uses: actions/checkout@v4
      
         -  name: Set up Docker Buildx
            uses: docker-practice/actions-setup-docker@master

         -  name: Log in to Dockerhub
            uses: docker/login-action@v1
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}

         -  name: Build And Push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
               push: true
               tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/pomd:latest

         -  name: image digest
            run: echo ${{ steps.docker_build.outputs.digest}}
   
   publish-tagged-image:
      needs: build-and-push
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest

      steps:
         -  name: Chekout code
            uses:   actions/checkout@v4

         -  name: Set up Docker Buildx
            uses:  docker-practice/actions-setup-docker@master

         -  name: Login to DockerHub
            uses: docker/login-action@v1
            with: 
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}

         -  name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with: 
               push: true
               tags:  |
                  ${{ secrets.DOCKERHUB_USERNAME }}/pomd:${{ github.ref_name }}

         -  name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}

   # deploy:
   #    needs: publish-tagged-image
   #    runs-on: ubuntu-latest
   #    steps:
   #       -  name: Checkout code
   #          uses: actions/checkout@v4
            
   #       -  name: Set up AWS Credentials
   #          uses: aws-actions/configure-aws-credentials@v2
   #          with:
   #             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
   #             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   #             aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Optional
   #             aws-region: us-east-1
               

   #       -  name: Set up Python
   #          uses: actions/setup-python@v5
   #          with:
   #             python-version: "3.9"

   #       -  name: Install Ansible
   #          run: pipx install --include-deps ansible

   #       -  name: Run Terraform
   #          run: |
   #             cd terraform
   #             terraform init
   #             terraform apply -auto-approve

   #       -  name: Run Ansible Playbook
   #          run: ansible-playbook ansible/main.yml -vvvv